POST http://localhost:5000/api_1.0/auth/register 
Content-Type: application/json

{
    "email":"z@gmail.com",
    "username":"z",
    "password":"123456"
}

###
POST http://localhost:5000/api_1.0/auth/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"123456"
}

###
POST http://localhost:5000/api_1.0/auth/logout

###
GET http://localhost:5000/api_1.0/user